# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='track',
            name='duration_sec',
            field=models.IntegerField(default=0),
        ),
    ]
